ARG NGINX_VERSION=1.25.3
FROM nginx:${NGINX_VERSION} as final
COPY --from=navystack/ngx_mod:${NGINX_VERSION} /usr/lib/nginx/modules/*.so /usr/lib/nginx/modules/
RUN mkdir -p /var/run/ngx_pagespeed_cache && \
    mkdir -p /var/run/nginx-cache && \
    chown www-data:www-data /var/run/ngx_pagespeed_cache && \
    chown www-data:www-data /var/run/nginx-cache && \
    rm -rf /etc/nginx/nginx.conf && \
    echo "load_module modules/ngx_http_immutable_module.so;\n$(cat /etc/nginx/nginx.conf)" > /etc/nginx/nginx.conf && \
    echo "load_module modules/ngx_http_cache_purge_module.so;\n$(cat /etc/nginx/nginx.conf)" > /etc/nginx/nginx.conf && \
    echo "load_module modules/ngx_http_brotli_static_module.so;\n$(cat /etc/nginx/nginx.conf)" > /etc/nginx/nginx.conf && \
    echo "load_module modules/ngx_http_brotli_filter_module.so;\n$(cat /etc/nginx/nginx.conf)" > /etc/nginx/nginx.conf && \
    echo "load_module modules/ngx_pagespeed.so;\n$(cat /etc/nginx/nginx.conf)" > /etc/nginx/nginx.conf