name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
      - "Dockerfile"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Push (Nginx With ngx_mod Module 1.26.0)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            navystack/ngx_mod:1.26.0
            navystack/ngx_mod:ngx_brotli-1.26.0
            navystack/ngx_mod:ngx_immutable-1.26.0
            navystack/ngx_mod:ngx_cache_purge-1.26.0
            navystack/ngx_mod:pagespeed-1.26.0
            navystack/ngx_mod:latest
          platforms: |
            linux/amd64
            linux/arm64
